{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "import mne\n",
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "#from surfer import Brain"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [],
   "source": [
    "os.environ['SUBJECTS_DIR'] = '/net/server/data/Archive/prob_learn/freesurfer'\n",
    "subjects_dir = '/net/server/data/Archive/prob_learn/freesurfer'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [],
   "source": [
    "subjects = pd.read_csv('/home/pultsinak/Рабочий стол/subj_list.csv')['subj_list'].tolist()\n",
    "subjects.remove('P062') \n",
    "subjects.remove('P052') \n",
    "subjects.remove(\"P032\")\n",
    "subjects.remove('P045') "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "rounds = [1, 2, 3, 4, 5, 6]\n",
    "freq_range = \"beta_16_30\"\n",
    "trial_type = ['norisk', 'prerisk', 'risk', 'postrisk']\n",
    "feedback = ['positive', 'negative']\n",
    "tmin = -0.700\n",
    "tmax = 2.501\n",
    "step = 0.1\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Reading labels from parcellation...\n",
      "   read 181 labels from /net/server/data/Archive/prob_learn/freesurfer/fsaverage/label/lh.HCPMMP1.annot\n",
      "   read 181 labels from /net/server/data/Archive/prob_learn/freesurfer/fsaverage/label/rh.HCPMMP1.annot\n"
     ]
    }
   ],
   "source": [
    "#parc that we used https://balsa.wustl.edu/WN56\n",
    "labels =  mne.read_labels_from_annot(\"fsaverage\", \"HCPMMP1\", hemi = \"both\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [],
   "source": [
    "os.makedirs('/net/server/data/Archive/prob_learn/pultsinak/label_stc/{0}_stc_fsaverage_epo_label_var2'.format(freq_range), exist_ok = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "This file not exist\n",
      "This file not exist\n",
      "This file not exist\n",
      "This file not exist\n",
      "This file not exist\n",
      "This file not exist\n",
      "This file not exist\n",
      "This file not exist\n",
      "17\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n",
      "[done]\n",
      "Writing STC to disk...\n"
     ]
    }
   ],
   "source": [
    "for subj in subjects:\n",
    "    for r in rounds:\n",
    "        for cond in trial_type:\n",
    "            for fb in feedback:\n",
    "                try:\n",
    "                    epochs_num = os.listdir('/net/server/data/Archive/prob_learn/vtretyakova/sources/{0}/beta_16_30_stc_epo_var2/{1}_run{2}_{3}_fb_cur_{4}_{0}'.format(freq_range, subj, r, cond, fb))\n",
    "                    print (int(len(epochs_num)/2))\n",
    "                    os.makedirs('/net/server/data/Archive/prob_learn/pultsinak/label_stc/{0}_stc_fsaverage_epo_label_var2/{1}_run{2}_{3}_fb_cur_{4}_{0}'.format(freq_range, subj, r, cond, fb))\n",
    "                \n",
    "                    for ep in range(int(len(epochs_num)/2)):\n",
    "                        stc = mne.read_source_estimate(\"/net/server/data/Archive/prob_learn/vtretyakova/sources/{0}/beta_16_30_stc_epo_var2/{1}_run{2}_{3}_fb_cur_{4}_{0}/{5}\".format(freq_range, subj, r, cond, fb, ep))\n",
    "                        stc_2 = stc.copy()\n",
    "                        for label in labels:\n",
    "                            stc_label = stc_2.in_label(label)\n",
    "                            stc_label.save('/net/server/data/Archive/prob_learn/pultsinak/label_stc/{0}_stc_fsaverage_epo_label_var2/{1}_run{2}_{3}_fb_cur_{4}_{0}/{5}_{6}'.format(freq_range, subj, r, cond, fb, ep,label))     \n",
    "                except (OSError):\n",
    "                    print('This file not exist')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
